version: '3'

services:
  django:
    &django
    image: 229301422682.dkr.ecr.ap-south-1.amazonaws.com/dev-html
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8089:8089
