version: '3'

services:
  django:
    &django
    image: ${DOCKER_REGISTER}/${DOCKER_IMAGE}-html
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8089:8089
